// import ProtectedRoute from "@/components/ProtectedRoute/ProtectedRoute";
// import "./globals.css";
// import { AuthContextProvider } from "@/context/AuthContext";

// export const metadata = {
//   title: "NinjaLig Technologies",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <html lang="en">
//       <body>
//         <AuthContextProvider>{children}</AuthContextProvider>
//       </body>
//     </html>
//   );
// }

import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import { AuthContextProvider } from "@/context/AuthContext";
import ProtectedRoute from "@/components/ProtectedRoute/ProtectedRoute";

export const metadata = {
  title: "NinjaLig Technologies",
  description: "Providing technological solutions for all your business needs.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthContextProvider>
          <Navbar />
          {children}
          <Footer />
        </AuthContextProvider>
      </body>
    </html>
  );
}
